// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwz4V7sH40JIjXAuOsCuH2DrSQ-xiadHA',
    appId: '1:540194297725:web:bef69349d3ed292a8a9e14',
    messagingSenderId: '540194297725',
    projectId: 'push-notify-demo-ae03c',
    authDomain: 'push-notify-demo-ae03c.firebaseapp.com',
    storageBucket: 'push-notify-demo-ae03c.appspot.com',
    measurementId: 'G-GQRWCW27ZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApGY6ZFhXxKxCDVTycYI4vFSX1ABe2TMw',
    appId: '1:540194297725:android:d6b1d4d5baf191d48a9e14',
    messagingSenderId: '540194297725',
    projectId: 'push-notify-demo-ae03c',
    storageBucket: 'push-notify-demo-ae03c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbMwvcVg-7qUlCxiaDh2oVIEwYY8PpBWs',
    appId: '1:540194297725:ios:95460b11ed1c2fc48a9e14',
    messagingSenderId: '540194297725',
    projectId: 'push-notify-demo-ae03c',
    storageBucket: 'push-notify-demo-ae03c.appspot.com',
    iosBundleId: 'com.PushNotification.Testing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbMwvcVg-7qUlCxiaDh2oVIEwYY8PpBWs',
    appId: '1:540194297725:ios:fbb35ff5e2bbe6db8a9e14',
    messagingSenderId: '540194297725',
    projectId: 'push-notify-demo-ae03c',
    storageBucket: 'push-notify-demo-ae03c.appspot.com',
    iosBundleId: 'com.PushNotification.Testing.RunnerTests',
  );
}
